'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AppShell, type NavItem } from '../../components/app-shell';
import { api, patch, post, put, type Plan } from '../../lib/api';

const items: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: 'Gauge' }, { id: 'users', label: 'Users', icon: 'Users' }, { id: 'devices', label: 'Devices', icon: 'HardDrive' },
  { id: 'plans', label: 'Plans', icon: 'Package' }, { id: 'subscriptions', label: 'Subscriptions', icon: 'BadgeCheck' }, { id: 'usage', label: 'Usage', icon: 'Activity' },
  { id: 'orders', label: 'Orders', icon: 'ShoppingBag' }, { id: 'providers', label: 'Providers', icon: 'Server' }, { id: 'models', label: 'Models', icon: 'Boxes' },
  { id: 'releases', label: 'Releases', icon: 'Download' }, { id: 'audit', label: 'Audit', icon: 'ScrollText' }, { id: 'system', label: 'System', icon: 'Settings2' },
];
type Row = Record<string, unknown> & { id?: string };
const resourcePaths: Record<string, string> = { users: 'users', devices: 'devices', plans: 'plans', subscriptions: 'subscriptions', usage: 'usage', orders: 'orders', providers: 'providers', models: 'models', releases: 'releases', audit: 'audit' };
const columns: Record<string, string[]> = {
  users: ['email', 'role', 'status', 'createdAt'], devices: ['deviceName', 'platform', 'status', 'lastSeenAt'], plans: ['code', 'name', 'monthlyPrice', 'maxDevices', 'enabled'],
  subscriptions: ['userId', 'planId', 'status', 'currentPeriodEnd'], usage: ['userId', 'status', 'totalTokens', 'usageCredit', 'costKind', 'createdAt'],
  orders: ['orderNo', 'userId', 'amount', 'provider', 'status'], providers: ['name', 'code', 'enabled', 'baseUrl'], models: ['displayName', 'publicId', 'enabled', 'usageWeight'],
  releases: ['version', 'channel', 'platform', 'published', 'createdAt'], audit: ['action', 'targetType', 'targetId', 'createdAt'],
};
function display(value: unknown) { if (value === null || value === undefined) return '—'; if (typeof value === 'boolean') return value ? '是' : '否'; if (typeof value === 'string' && /^\d{4}-\d\d-\d\dT/.test(value)) return new Date(value).toLocaleString('zh-CN'); return String(value); }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div className="field"><label>{label}</label><input type={type} value={value} onChange={e => onChange(e.target.value)}/></div>; }

export default function AdminPage() {
  const router = useRouter(); const [active, setActive] = useState('dashboard'); const [email, setEmail] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [dashboard, setDashboard] = useState<Record<string, number>>({}); const [system, setSystem] = useState<Record<string, unknown>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Row | null>(null); const [form, setForm] = useState<Record<string, string>>({}); const [plans, setPlans] = useState<Plan[]>([]); const [providers, setProviders] = useState<Row[]>([]); const [models, setModels] = useState<Row[]>([]);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const me = await api<{ user: { email: string; role: string } }>('/api/v1/auth/me');
      if (me.user.role !== 'ADMIN') { router.replace('/dashboard'); return; }
      setEmail(me.user.email);
      if (active === 'dashboard') setDashboard(await api<Record<string, number>>('/api/v1/admin/dashboard'));
      else if (active === 'system') setSystem(await api<Record<string, unknown>>('/api/v1/admin/system'));
      else { const result = await api<{ data: Row[] }>(`/api/v1/admin/${resourcePaths[active]}${active === 'users' && search ? `?search=${encodeURIComponent(search)}` : ''}`); setRows(result.data); }
      if (active === 'models') { const [p, m] = await Promise.all([api<{ data: Plan[] }>('/api/v1/admin/plans'), api<{ data: Row[] }>('/api/v1/admin/providers')]); setPlans(p.data); setProviders(m.data); }
      if (active === 'subscriptions') { const p = await api<{ data: Plan[] }>('/api/v1/admin/plans'); setPlans(p.data); }
      if (active === 'providers') { const m = await api<{ data: Row[] }>('/api/v1/admin/models'); setModels(m.data); }
    } catch (e) { setError((e as { message?: string }).message ?? '暂时无法加载'); }
    finally { setLoading(false); }
  }, [active, router, search]);
  useEffect(() => { void load(); }, [load]);
  function update(key: string, value: string) { setForm(prev => ({ ...prev, [key]: value })); }
  async function run(action: () => Promise<unknown>, success = '已保存') { setMessage(''); try { await action(); setMessage(success); setSelected(null); await load(); } catch (e) { setMessage((e as { message?: string }).message ?? '操作失败'); } }
  const title = items.find(i => i.id === active)?.label ?? 'Admin';
  return <AppShell title={title} description="管理账号、权限、订阅与服务状态。" items={items} active={active} onChange={id => {setActive(id);setSelected(null);setForm({});setSearch('');setMessage('');}} email={email || 'Admin'} admin>
    {message && <div className="notice" role="status">{message}</div>}{error && <div className="error-text" role="alert">{error} <button className="mini-button" onClick={load}>重试</button></div>}
    {loading && <div className="loading-skeleton"/>}
    {!loading && active === 'dashboard' && <div className="stat-grid">{Object.entries(dashboard).map(([key, value]) => <div className="stat" key={key}><span className="stat-label">{key.toUpperCase()}</span><strong>{value}</strong></div>)}</div>}
    {!loading && active === 'system' && <section className="panel"><h2>系统诊断</h2><p>Database: {display(system.database)}</p><p>Gateway: {display(system.gateway)}</p><p>配置项：{Array.isArray(system.settings) ? system.settings.length : 0}</p></section>}
    {!loading && resourcePaths[active] && <><div className="toolbar"><h2>{title} <span style={{fontSize:12,color:'#9aa69b'}}>({rows.length})</span></h2>{active === 'users' && <input className="search-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索邮箱" aria-label="搜索用户"/>}</div><section className="panel" style={{marginTop:0,padding:0}}>{rows.length ? <div className="table-wrap"><table className="data-table"><thead><tr>{columns[active]?.map(c => <th key={c}>{c}</th>)}<th>操作</th></tr></thead><tbody>{rows.map((row, idx) => <tr key={row.id ?? idx}>{columns[active]?.map(c => <td key={c}>{c === 'status' || c === 'enabled' || c === 'published' ? <span className={`badge ${row[c] === 'ACTIVE' || row[c] === true || row[c] === 'COMPLETED' ? '' : 'muted'}`}>{display(row[c])}</span> : display(row[c])}</td>)}<td><div className="inline-actions">
      {['users','plans','providers','models','releases'].includes(active) && <button className="mini-button" onClick={() => {setSelected(row);setForm({});}}>管理</button>}
      {active === 'devices' && <button className="mini-button" onClick={() => run(() => patch(`/api/v1/admin/devices/${row.id}`, { status: row.status === 'ACTIVE' ? 'REVOKED' : 'ACTIVE' }))}>{row.status === 'ACTIVE' ? '停用' : '恢复'}</button>}
      {active === 'orders' && row.status === 'PENDING' && row.provider === 'MANUAL' && <button className="mini-button" onClick={() => run(() => post(`/api/v1/admin/orders/${row.id}/mark-paid`, {}), '手工订单已入账')}>确认收款</button>}
      {active === 'subscriptions' && <button className="mini-button" onClick={() => {setSelected(row);setForm({});}}>调整</button>}
    </div></td></tr>)}</tbody></table></div> : <div className="empty"><strong>暂无记录</strong>新数据出现后会显示在这里。</div>}</section></>}

    {active === 'users' && <section className="panel"><h2>创建用户</h2><div className="form-grid"><Field label="邮箱" type="email" value={form.email ?? ''} onChange={v => update('email',v)}/><Field label="初始密码（至少 12 位）" type="password" value={form.password ?? ''} onChange={v => update('password',v)}/></div><button className="button button-small" onClick={() => run(() => post('/api/v1/admin/users', { email: form.email, password: form.password, role: 'USER' }), '用户已创建')}>创建用户</button></section>}
    {active === 'users' && selected && <section className="panel"><h2>{display(selected.email)}</h2><p>ID: {selected.id} · {display(selected.role)} · {display(selected.status)}</p><div className="inline-actions"><button className="mini-button" onClick={() => run(() => patch(`/api/v1/admin/users/${selected.id}`, { status: selected.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }))}>{selected.status === 'ACTIVE' ? '禁用用户' : '恢复用户'}</button></div><div className="form-grid"><Field label="新密码（至少 12 位）" type="password" value={form.newPassword ?? ''} onChange={v => update('newPassword',v)}/></div><button className="mini-button" onClick={() => run(() => post(`/api/v1/admin/users/${selected.id}/reset-password`, {password:form.newPassword}), '密码已重置')}>重置密码</button><div className="form-grid"><Field label="模型 ID（数据库 UUID）" value={form.overrideModelId ?? ''} onChange={v => update('overrideModelId',v)}/><div className="field"><label>权限</label><select value={form.override ?? 'ALLOW'} onChange={e => update('override',e.target.value)}><option>ALLOW</option><option>DENY</option><option>DEFAULT</option></select></div></div><button className="mini-button" onClick={() => run(() => put(`/api/v1/admin/users/${selected.id}/models/${form.overrideModelId}`, {access:form.override ?? 'ALLOW'}))}>设置模型特例</button></section>}

    {active === 'plans' && selected && <section className="panel"><h2>编辑 {display(selected.code)}</h2><div className="form-grid">{[['name','名称'],['description','描述'],['monthlyPrice','月费'],['currency','货币'],['maxDevices','设备上限'],['monthlyTokenLimit','月 Token 上限'],['monthlyUsageCreditLimit','月 Credit 上限'],['maxConcurrentRequests','最大并发'],['requestsPerMinute','每分钟请求']].map(([key,label]) => <Field key={key} label={label} value={form[key] ?? display(selected[key])} onChange={v => update(key,v)}/>)}</div><label style={{fontSize:12}}><input type="checkbox" checked={(form.enabled ?? String(selected.enabled)) === 'true'} onChange={e => update('enabled', String(e.target.checked))}/> 启用套餐</label><div className="form-actions"><button className="button button-small" onClick={() => run(() => patch(`/api/v1/admin/plans/${selected.id}`, { name: form.name ?? selected.name, description: form.description ?? selected.description, monthlyPrice: Number(form.monthlyPrice ?? selected.monthlyPrice), currency: form.currency ?? selected.currency, maxDevices: Number(form.maxDevices ?? selected.maxDevices), monthlyTokenLimit: Number(form.monthlyTokenLimit ?? selected.monthlyTokenLimit), monthlyUsageCreditLimit: Number(form.monthlyUsageCreditLimit ?? selected.monthlyUsageCreditLimit), maxConcurrentRequests: Number(form.maxConcurrentRequests ?? selected.maxConcurrentRequests), requestsPerMinute: Number(form.requestsPerMinute ?? selected.requestsPerMinute), enabled: (form.enabled ?? String(selected.enabled)) === 'true' }))}>保存套餐</button></div></section>}

    {active === 'subscriptions' && <section className="panel"><h2>手工开通</h2><div className="form-grid"><Field label="用户 UUID" value={form.userId ?? ''} onChange={v => update('userId',v)}/><div className="field"><label>套餐</label><select value={form.planCode ?? 'STANDARD'} onChange={e => update('planCode',e.target.value)}>{plans.map(p => <option key={p.id}>{p.code}</option>)}</select></div><Field label="天数" type="number" value={form.days ?? '30'} onChange={v => update('days',v)}/></div><button className="button button-small" onClick={() => run(() => post('/api/v1/admin/subscriptions/grant', { userId: form.userId, planCode: form.planCode ?? 'STANDARD', days: Number(form.days ?? 30) }), '订阅已开通')}>开通订阅</button></section>}
    {active === 'subscriptions' && selected && <section className="panel"><h2>调整订阅</h2><p>{selected.id}</p><div className="form-grid"><div className="field"><label>操作</label><select value={form.action ?? 'EXTEND'} onChange={e => update('action',e.target.value)}>{['EXTEND','SUSPEND','CANCEL','UPGRADE','DOWNGRADE'].map(v => <option key={v}>{v}</option>)}</select></div><Field label="延长天数" type="number" value={form.days ?? '30'} onChange={v => update('days',v)}/><div className="field"><label>目标套餐</label><select value={form.planCode ?? 'PRO'} onChange={e => update('planCode',e.target.value)}>{plans.map(p => <option key={p.id}>{p.code}</option>)}</select></div></div><button className="button button-small" onClick={() => run(() => patch(`/api/v1/admin/subscriptions/${selected.id}`, { action: form.action ?? 'EXTEND', days: Number(form.days ?? 30), planCode: form.planCode ?? 'PRO' }))}>应用调整</button></section>}

    {active === 'providers' && selected && <section className="panel"><h2>{display(selected.name)}</h2><p>API Key 保存后只显示掩码。Copilot Provider 在授权评审前保持禁用。</p><div className="form-grid"><Field label="Base URL" value={form.baseUrl ?? String(selected.baseUrl ?? '')} onChange={v => update('baseUrl',v)}/><Field label="超时（毫秒）" type="number" value={form.timeoutMs ?? String(selected.timeoutMs ?? 60000)} onChange={v => update('timeoutMs',v)}/><Field label="新 API Key（留空则不修改）" type="password" value={form.apiKey ?? ''} onChange={v => update('apiKey',v)}/></div><label style={{fontSize:12}}><input type="checkbox" checked={(form.enabled ?? String(selected.enabled)) === 'true'} onChange={e => update('enabled',String(e.target.checked))}/> 启用 Provider</label><div className="form-actions"><button className="button button-small" onClick={() => run(() => patch(`/api/v1/admin/providers/${selected.id}`, {enabled:(form.enabled ?? String(selected.enabled)) === 'true',baseUrl:form.baseUrl || selected.baseUrl || undefined,timeoutMs:Number(form.timeoutMs ?? selected.timeoutMs),apiKey:form.apiKey || undefined}))}>保存 Provider</button><button className="mini-button" onClick={() => run(async () => { const result = await api<{ready:boolean;reason?:string}>(`/api/v1/admin/providers/${selected.id}/health`); setMessage(result.ready ? 'Provider 正常' : `Provider 不可用：${result.reason}`); })}>健康检查</button></div><p>已配置模型：{models.filter(m => m.providerId === selected.id).length}</p></section>}

    {active === 'models' && <section className="panel"><h2>添加模型</h2><div className="form-grid"><div className="field"><label>Provider</label><select value={form.providerId ?? String(providers[0]?.id ?? '')} onChange={e => update('providerId',e.target.value)}>{providers.map(p => <option key={p.id} value={String(p.id)}>{display(p.name)}</option>)}</select></div><Field label="Provider Model ID" value={form.providerModelId ?? ''} onChange={v => update('providerModelId',v)}/><Field label="公开 ID（例如 deepseek/model）" value={form.publicId ?? ''} onChange={v => update('publicId',v)}/><Field label="显示名称" value={form.displayName ?? ''} onChange={v => update('displayName',v)}/></div><button className="button button-small" onClick={() => run(() => post('/api/v1/admin/models', { providerId: form.providerId ?? providers[0]?.id, providerModelId: form.providerModelId, publicId: form.publicId, displayName: form.displayName, enabled: false, supportsTools: true, supportsVision: false, supportsReasoning: false, supportsStreaming: true, contextWindow: null, maxOutputTokens: null, usageWeight: 1, sortOrder: 0 }), '模型已添加')}>添加模型</button></section>}
    {active === 'models' && selected && <section className="panel"><h2>{display(selected.displayName)}</h2><p>{display(selected.publicId)}</p><div className="inline-actions"><button className="mini-button" onClick={() => run(() => patch(`/api/v1/admin/models/${selected.id}`, { enabled: !selected.enabled }))}>{selected.enabled ? '停用模型' : '启用模型'}</button></div><div className="form-grid"><Field label="Usage Weight" type="number" value={form.usageWeight ?? String(selected.usageWeight)} onChange={v => update('usageWeight',v)}/></div><button className="mini-button" onClick={() => run(() => patch(`/api/v1/admin/models/${selected.id}`, { usageWeight: Number(form.usageWeight ?? selected.usageWeight) }))}>保存权重</button><h3 style={{fontSize:14,marginTop:30}}>套餐权限</h3>{plans.map(p => <div className="inline-actions" style={{marginBottom:9}} key={p.id}><span style={{minWidth:90,fontSize:12}}>{p.name}</span><button className="mini-button" onClick={() => run(() => put(`/api/v1/admin/models/${selected.id}/plans/${p.id}`, {allowed:true}), `${p.name} 已开放`)}>开放</button><button className="mini-button danger" onClick={() => run(() => put(`/api/v1/admin/models/${selected.id}/plans/${p.id}`, {allowed:false}), `${p.name} 已关闭`)}>关闭</button></div>)}</section>}

    {active === 'releases' && <section className="panel"><h2>创建 Release</h2><div className="form-grid">{[['version','版本'],['channel','频道（stable / beta）'],['platform','平台'],['arch','架构'],['downloadUrl','下载 URL'],['sha256','SHA256'],['releaseNotes','发布说明']].map(([key,label]) => <Field key={key} label={label} value={form[key] ?? ''} onChange={v => update(key,v)}/>)}</div><button className="button button-small" onClick={() => run(() => post('/api/v1/admin/releases', { version:form.version,channel:form.channel || 'stable',platform:form.platform || 'windows',arch:form.arch || 'x64',downloadUrl:form.downloadUrl,sha256:form.sha256,releaseNotes:form.releaseNotes || '',published:false }), 'Release 已创建')}>创建草稿</button></section>}
    {active === 'releases' && selected && <section className="panel"><h2>{display(selected.version)}</h2><p>{display(selected.downloadUrl)}</p><button className="button button-small" onClick={() => run(() => patch(`/api/v1/admin/releases/${selected.id}`, {published:!selected.published}), selected.published ? '已取消发布' : '已发布')}>{selected.published ? '取消发布' : '发布'}</button></section>}
  </AppShell>;
}
