import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, CircleDot, Command, Laptop2, Layers3, LockKeyhole, MoveUpRight, Sparkles, Terminal, Workflow } from 'lucide-react';
import { SiteHeader } from '../components/site-header';

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> CHATGPT DESKTOP × COPILOT BRIDGE</div><h1>让桌面工作，<br/><em>从官方 ChatGPT Desktop 出发。</em></h1><p className="hero-lede">继续使用官方 ChatGPT 桌面客户端。Copilot Bridge 在本地准备独立环境，连接你有权限使用的 GitHub Copilot 或 Cloud 模型；无需手动配置代理或运行命令行。</p><div className="hero-actions"><Link href="/download" className="button">了解 Windows 版 <ArrowRight size={18}/></Link><Link href="/#how-it-works" className="button-quiet">看看如何使用 <ArrowUpRight size={16}/></Link></div><div className="hero-note"><span className="mini-status"/> 使用前仍需能够正常安装并登录官方 ChatGPT Desktop；切换环境需按提示重新登录 Windows</div></div>
    <div className="hero-visual" role="img" aria-label="原创示意图：官方 ChatGPT Desktop 连接本地 Copilot Bridge，选择有权限的模型，并由桌面客户端执行本地工具"><div className="visual-top"><span className="visual-dots"><i/><i/><i/></span><span>CHATGPT DESKTOP / BRIDGE</span><span><Command size={14}/></span></div><div className="visual-body"><div className="visual-rail"><span className="rail-active"><Layers3 size={18}/></span><span><Workflow size={18}/></span><span><Terminal size={18}/></span></div><div className="visual-content"><div className="visual-tag">独立的工作环境 <span/></div><h3>你熟悉的桌面，<br/>接入可用的模型。</h3><p className="visual-prompt">“整理这个项目的接口文档，并更新缺失的测试。”</p><div className="visual-flow"><div><span className="flow-icon"><Laptop2 size={17}/></span><div><strong>官方 ChatGPT Desktop</strong><small>保留原有账号与使用习惯</small></div><Check size={15}/></div><div><span className="flow-icon"><Sparkles size={17}/></span><div><strong>Copilot Bridge</strong><small>在本地切换独立环境与已授权模型</small></div><Check size={15}/></div><div><span className="flow-icon"><CircleDot size={17}/></span><div><strong>本地工具</strong><small>文件和命令在你的电脑上执行</small></div><span className="active-pulse"/></div></div></div></div><div className="visual-foot"><LockKeyhole size={13}/> 原创流程示意；不是 ChatGPT 官方界面的截图</div></div></section>
    <section className="trust-strip"><div className="container trust-inner"><span>把两套环境清楚分开</span><div><span>原账号保留</span><span>本地 Copilot 无需 Cloud 注册</span><span>可恢复原环境</span><span>工具在本地执行</span></div></div></section>
    <section id="how-it-works" className="section container"><div className="section-heading"><span className="eyebrow">THREE SIMPLE STEPS</span><h2>少做设置，<br/>清楚知道自己在用什么。</h2><p>安装 Copilot Bridge 后检查官方 ChatGPT Desktop。连接自己的 GitHub Copilot，或在账号开通后使用 Cloud。选择独立环境并按提示注销、重新登录 Windows 后生效。</p></div><div className="feature-grid"><article><span className="feature-icon"><Laptop2 size={21}/></span><span className="feature-number">01 / PREPARE</span><h3>准备官方桌面客户端</h3><p>继续在官方 ChatGPT Desktop 中工作；Bridge 会帮助检查安装状态。需要官方客户端可在你的网络环境正常安装与登录。</p><Link href="/download">了解安装 <MoveUpRight size={15}/></Link></article><article><span className="feature-icon"><Sparkles size={21}/></span><span className="feature-number">02 / CONNECT</span><h3>选择你有权限的服务</h3><p>已有 GitHub Copilot 可直接使用本地模式，不必注册 Cloud。Cloud 是独立的可选服务，目前需管理员测试开通。</p><Link href="/pricing">了解 Cloud 状态 <MoveUpRight size={15}/></Link></article><article><span className="feature-icon"><LockKeyhole size={21}/></span><span className="feature-number">03 / SWITCH</span><h3>切换，也能恢复原账号</h3><p>原账号和 Bridge 的会话、工作区彼此隔离。切换后按 App 提示注销并重新登录 Windows，回来即可确认实际生效状态。</p><Link href="/download">查看使用步骤 <MoveUpRight size={15}/></Link></article></div></section>
    <section className="statement"><div className="container statement-inner"><div><span className="eyebrow">ONE DESKTOP, CLEAR CHOICES</span><h2>保留原来的桌面，<br/>按需连接新能力。</h2></div><div><p>Copilot Bridge 不是 ChatGPT 官方产品，也不改变你原账号的数据。模型由你选择的服务提供；Cloud 推理与本地工具执行有明确边界。</p><Link href="/download" className="button button-light">了解 Copilot Bridge <ArrowRight size={17}/></Link></div></div></section>
  </main><footer className="footer container"><div className="brand"><span className="brand-mark"><Layers3 size={17}/></span> Copilot Bridge Cloud</div><div><Link href="/pricing">套餐</Link><Link href="/download">下载</Link><Link href="/dashboard">用户中心</Link></div><small>© {new Date().getFullYear()} Copilot Bridge Cloud · 非 ChatGPT 官方产品</small></footer></>;
}
