import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, CircleDot, Command, Laptop2, Layers3, LockKeyhole, MoveUpRight, Sparkles, Terminal, Workflow } from 'lucide-react';
import { SiteHeader } from '../components/site-header';

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> DESKTOP AGENT, CONNECTED</div><h1>让桌面工作，<br/><em>进入下一步。</em></h1><p className="hero-lede">连接你信任的在线模型，让 Copilot Bridge 在本地完成文件、代码和工具操作。一个账号，管理模型、设备与用量。</p><div className="hero-actions"><Link href="/download" className="button">下载 Windows 版 <ArrowRight size={18}/></Link><Link href="/#how-it-works" className="button-quiet">了解工作方式 <ArrowUpRight size={16}/></Link></div><div className="hero-note"><span className="mini-status"/> 云端推理与本地执行，各司其职</div></div>
    <div className="hero-visual" aria-label="Copilot Bridge 工作流程示意"><div className="visual-top"><span className="visual-dots"><i/><i/><i/></span><span>WORKSPACE / BRIDGE</span><span><Command size={14}/></span></div><div className="visual-body"><div className="visual-rail"><span className="rail-active"><Layers3 size={18}/></span><span><Workflow size={18}/></span><span><Terminal size={18}/></span></div><div className="visual-content"><div className="visual-tag">ACTIVE SESSION <span/></div><h3>从想法，到完成。</h3><p className="visual-prompt">“整理这个项目的接口文档，并更新缺失的测试。”</p><div className="visual-flow"><div><span className="flow-icon"><Sparkles size={17}/></span><div><strong>Cloud model</strong><small>理解任务并规划步骤</small></div><Check size={15}/></div><div><span className="flow-icon"><Laptop2 size={17}/></span><div><strong>Local agent</strong><small>在你的电脑上执行操作</small></div><Check size={15}/></div><div><span className="flow-icon"><CircleDot size={17}/></span><div><strong>Review</strong><small>更改清晰可见，由你决定</small></div><span className="active-pulse"/></div></div></div></div><div className="visual-foot"><LockKeyhole size={13}/> 本地文件操作留在 Desktop</div></div></section>
    <section className="trust-strip"><div className="container trust-inner"><span>为真实工作流设计</span><div><span>模型访问控制</span><span>设备管理</span><span>用量透明</span><span>本地工具边界</span></div></div></section>
    <section id="how-it-works" className="section container"><div className="section-heading"><span className="eyebrow">BUILT FOR THE WAY YOU WORK</span><h2>强大的模型，<br/>仍然由你掌控。</h2><p>Cloud 负责账号、模型和推理。Desktop 连接本地工具，所有文件操作都在你的电脑上发生。</p></div><div className="feature-grid"><article><span className="feature-icon"><Sparkles size={21}/></span><span className="feature-number">01 / MODEL</span><h3>按需选择模型</h3><p>在一个入口访问已开放的模型。套餐与个人权限清晰管理，随时了解哪些能力可用。</p><Link href="/pricing">查看套餐 <MoveUpRight size={15}/></Link></article><article><span className="feature-icon"><Laptop2 size={21}/></span><span className="feature-number">02 / DESKTOP</span><h3>让 Agent 在本地工作</h3><p>读取、编辑、创建与命令执行由 Desktop 本地完成。云端只接收模型推理所需上下文。</p><Link href="/download">了解 Desktop <MoveUpRight size={15}/></Link></article><article><span className="feature-icon"><LockKeyhole size={21}/></span><span className="feature-number">03 / CONTROL</span><h3>知道每一步的状态</h3><p>设备、订阅和本月用量集中呈现。管理员可管理模型开放范围与服务状态。</p><Link href="/dashboard">打开用户中心 <MoveUpRight size={15}/></Link></article></div></section>
    <section className="statement"><div className="container statement-inner"><div><span className="eyebrow">A BETTER BRIDGE</span><h2>你的工作台，<br/>现在可以走得更远。</h2></div><div><p>Copilot Bridge Cloud 让在线模型与桌面 Agent 顺畅协作，同时保留清晰的本地工具边界。</p><Link href="/download" className="button button-light">获取 Copilot Bridge <ArrowRight size={17}/></Link></div></div></section>
  </main><footer className="footer container"><div className="brand"><span className="brand-mark"><Layers3 size={17}/></span> Copilot Bridge Cloud</div><div><Link href="/pricing">套餐</Link><Link href="/download">下载</Link><Link href="/login">登录</Link></div><small>© {new Date().getFullYear()} Copilot Bridge Cloud</small></footer></>;
}
